'use strict';

import CommonConstants                from '../commonConstants';

export default {
  URL_API : CommonConstants.BASE_URL_API,
  URL_IMAGE : CommonConstants.BASE_URL_IMAGE,
  CREATE_CONFERENCE_SCHEDULE_EVENT: 'CREATE_CONFERENCE_SCHEDULE_EVENT',
  READ_CONFERENCE_SCHEDULE_EVENT: 'READ_CONFERENCE_SCHEDULE_EVENT',
  SAVE_CONFERENCE_SCHEDULE_EVENT: 'SAVE_CONFERENCE_SCHEDULE_EVENT',
  DELETE_CONFERENCE_SCHEDULE_EVENT: 'DELETE_CONFERENCE_SCHEDULE_EVENT',
  LIST_CONFERENCE_SCHEDULE_EVENT: 'LIST_CONFERENCE_SCHEDULE_EVENT',

  // trigger when success or errors
  SAVED_CONFERENCE_SCHEDULE_EVENT: 'SAVED_CONFERENCE_SCHEDULE_EVENT',
  DELETED_CONFERENCE_SCHEDULE_EVENT: 'DELETED_CONFERENCE_SCHEDULE_EVENT',
  ERROR_SAVE_CONFERENCE_SCHEDULE_EVENT: 'ERROR_SAVE_CONFERENCE_SCHEDULE_EVENT',
  ERROR_DELETE_CONFERENCE_SCHEDULE_EVENT: 'ERROR_DELETE_CONFERENCE_SCHEDULE_EVENT'
};