'use strict';

let BASE_URL = 'http://localhost:3000/';

export default {
  URL: BASE_URL + 'api/conferences',
  CREATE_CONFERENCE_SCHEDULE_EVENT: 'CREATE_CONFERENCE_SCHEDULE_EVENT',
  READ_CONFERENCE_SCHEDULE_EVENT: 'READ_CONFERENCE_SCHEDULE_EVENT',
  SAVE_CONFERENCE_SCHEDULE_EVENT: 'SAVE_CONFERENCE_SCHEDULE_EVENT',
  DELETE_CONFERENCE_SCHEDULE_EVENT: 'DELETE_CONFERENCE_SCHEDULE_EVENT',
  LIST_CONFERENCE_SCHEDULE_EVENT: 'LIST_CONFERENCE_SCHEDULE_EVENT',

  // trigger when success or errors
  SAVED_CONFERENCE_SCHEDULE_EVENT: 'SAVED_CONFERENCE_SCHEDULE_EVENT',
  DELETED_CONFERENCE_SCHEDULE_EVENT: 'DELETED_CONFERENCE_SCHEDULE_EVENT',
  ERROR_SAVE_CONFERENCE_SCHEDULE_EVENT: 'ERROR_SAVE_CONFERENCE_SCHEDULE_EVENT',
  ERROR_DELETE_CONFERENCE_SCHEDULE_EVENT: 'ERROR_DELETE_CONFERENCE_SCHEDULE_EVENT'
};