'use strict';

import CommonConstants                from '../commonConstants';

export default {
  URL_API : CommonConstants.BASE_URL_API,
  URL_IMAGE : CommonConstants.BASE_URL_IMAGE,
  CREATE_COURSE_TYPE_EVENT: 'CREATE_COURSE_TYPE_EVENT',
  READ_COURSE_TYPE_EVENT: 'READ_COURSE_TYPE_EVENT',
  SAVE_COURSE_TYPE_EVENT: 'SAVE_COURSE_TYPE_EVENT',
  DELETE_COURSE_TYPE_EVENT: 'DELETE_COURSE_TYPE_EVENT',
  LIST_COURSE_TYPE_EVENT: 'LIST_COURSE_TYPE_EVENT',

  // trigger when success or errors
  SAVED_COURSE_TYPE_EVENT: 'SAVED_COURSE_TYPE_EVENT',
  DELETED_COURSE_TYPE_EVENT: 'DELETED_COURSE_TYPE_EVENT',
  ERROR_SAVE_COURSE_TYPE_EVENT: 'ERROR_SAVE_COURSE_TYPE_EVENT',
  ERROR_DELETE_COURSE_TYPE_EVENT: 'ERROR_DELETE_COURSE_TYPE_EVENT'
};