'use strict';

import CommonConstants                from '../commonConstants';

export default {
  URL_API : CommonConstants.BASE_URL_API,
  URL_IMAGE : CommonConstants.BASE_URL_IMAGE,
  CREATE_FREE_DAY_EVENT: 'CREATE_FREE_DAY_EVENT',
  READ_FREE_DAY_EVENT: 'READ_FREE_DAY_EVENT',
  SAVE_FREE_DAY_EVENT: 'SAVE_FREE_DAY_EVENT',
  DELETE_FREE_DAY_EVENT: 'DELETE_FREE_DAY_EVENT',
  LIST_FREE_DAY_EVENT: 'LIST_FREE_DAY_EVENT',

  // trigger when success or errors
  SAVED_FREE_DAY_EVENT: 'SAVED_FREE_DAY_EVENT',
  DELETED_FREE_DAY_EVENT: 'DELETED_FREE_DAY_EVENT',
  ERROR_SAVE_FREE_DAY_EVENT: 'ERROR_SAVE_FREE_DAY_EVENT',
  ERROR_DELETE_FREE_DAY_EVENT: 'ERROR_DELETE_FREE_DAY_EVENT'
};