'use strict';

let BASE_URL = 'http://localhost:3000/api/';

export default {
  BASE_URL: BASE_URL,
  CREATE_FREE_DAY_EVENT: 'CREATE_FREE_DAY_EVENT',
  READ_FREE_DAY_EVENT: 'READ_FREE_DAY_EVENT',
  SAVE_FREE_DAY_EVENT: 'SAVE_FREE_DAY_EVENT',
  DELETE_FREE_DAY_EVENT: 'DELETE_FREE_DAY_EVENT',
  LIST_FREE_DAY_EVENT: 'LIST_FREE_DAY_EVENT',

  // trigger when success or errors
  SAVED_FREE_DAY_EVENT: 'SAVED_FREE_DAY_EVENT',
  DELETED_FREE_DAY_EVENT: 'DELETED_FREE_DAY_EVENT',
  ERROR_SAVE_FREE_DAY_EVENT: 'ERROR_SAVE_FREE_DAY_EVENT',
  ERROR_DELETE_FREE_DAY_EVENT: 'ERROR_DELETE_FREE_DAY_EVENT'
};