'use strict';

import CommonConstants                from '../commonConstants';

export default {
  URL_API : CommonConstants.BASE_URL_API,
  URL_IMAGE : CommonConstants.BASE_URL_IMAGE,
  CREATE_SCHEDULE_EVENT: 'CREATE_SCHEDULE_EVENT',
  READ_SCHEDULE_EVENT: 'READ_SCHEDULE_EVENT',
  SAVE_SCHEDULE_EVENT: 'SAVE_SCHEDULE_EVENT',
  DELETE_SCHEDULE_EVENT: 'DELETE_SCHEDULE_EVENT',
  LIST_SCHEDULE_EVENT: 'LIST_SCHEDULE_EVENT',

  // trigger when success or errors
  SAVED_SCHEDULE_EVENT: 'SAVED_SCHEDULE_EVENT',
  DELETED_SCHEDULE_EVENT: 'DELETED_SCHEDULE_EVENT',
  ERROR_SAVE_SCHEDULE_EVENT: 'ERROR_SAVE_SCHEDULE_EVENT',
  ERROR_DELETE_SCHEDULE_EVENT: 'ERROR_DELETE_SCHEDULE_EVENT'
};