'use strict';

import CommonConstants                from '../commonConstants';

export default {
  URL_API : CommonConstants.BASE_URL_API,
  URL_IMAGE : CommonConstants.BASE_URL_IMAGE,
  CREATE_TEACHER_EVENT: 'CREATE_TEACHER_EVENT',
  READ_TEACHER_EVENT: 'READ_TEACHER_EVENT',
  SAVE_TEACHER_EVENT: 'SAVE_TEACHER_EVENT',
  DELETE_TEACHER_EVENT: 'DELETE_TEACHER_EVENT',
  LIST_TEACHER_EVENT: 'LIST_TEACHER_EVENT',

  // trigger when success or errors
  SAVED_TEACHER_EVENT: 'SAVED_TEACHER_EVENT',
  DELETED_TEACHER_EVENT: 'DELETED_TEACHER_EVENT',
  ERROR_SAVE_TEACHER_EVENT: 'ERROR_SAVE_TEACHER_EVENT',
  ERROR_DELETE_TEACHER_EVENT: 'ERROR_DELETE_TEACHER_EVENT'
};