'use strict';

let BASE_URL = 'http://localhost:3000/api/';

export default {
  BASE_URL: BASE_URL,
  CREATE_COURSE_DESCRIPTION_EVENT: 'CREATE_COURSE_DESCRIPTION_EVENT',
  READ_COURSE_DESCRIPTION_EVENT: 'READ_COURSE_DESCRIPTION_EVENT',
  SAVE_COURSE_DESCRIPTION_EVENT: 'SAVE_COURSE_DESCRIPTION_EVENT',
  DELETE_COURSE_DESCRIPTION_EVENT: 'DELETE_COURSE_DESCRIPTION_EVENT',
  GET_COURSE_DESCRIPTION_EVENT: 'GET_COURSE_DESCRIPTION_EVENT',

  // trigger when success or errors
  SAVED_COURSE_DESCRIPTION_EVENT: 'SAVED_COURSE_DESCRIPTION_EVENT',
  DELETED_COURSE_DESCRIPTION_EVENT: 'DELETED_COURSE_DESCRIPTION_EVENT',
  ERROR_SAVE_COURSE_DESCRIPTION_EVENT: 'ERROR_SAVE_COURSE_DESCRIPTION_EVENT',
  ERROR_DELETE_COURSE_DESCRIPTION_EVENT: 'ERROR_DELETE_COURSE_DESCRIPTION_EVENT'
};