'use strict';

let BASE_URL = 'http://localhost:3000/';

export default {
  URL: BASE_URL + 'api/courses',
  CREATE_COURSE_NAME_EVENT: 'CREATE_COURSE_NAME_EVENT',
  READ_COURSE_NAME_EVENT: 'READ_COURSE_NAME_EVENT',
  SAVE_COURSE_NAME_EVENT: 'SAVE_COURSE_NAME_EVENT',
  DELETE_COURSE_NAME_EVENT: 'DELETE_COURSE_NAME_EVENT',
  LIST_COURSE_NAME_EVENT: 'LIST_COURSE_NAME_EVENT',

  // trigger when success or errors
  SAVED_COURSE_NAME_EVENT: 'SAVED_COURSE_NAME_EVENT',
  DELETED_COURSE_NAME_EVENT: 'DELETED_COURSE_NAME_EVENT',
  ERROR_SAVE_COURSE_NAME_EVENT: 'ERROR_SAVE_COURSE_NAME_EVENT',
  ERROR_DELETE_COURSE_NAME_EVENT: 'ERROR_DELETE_COURSE_NAME_EVENT'
};